## Summary:  
Software: openstack/nova  
## Fix:  
Commit: https://github.com/openstack/nova/commit/3bf177a59cfd0b4e74dba256c3466ba2ea9bfbf7  
Change Size: +4 -0  
Fix Time (of the Last Commit): 2017-03-17  
Author: Balazs Gibizer  
Fix Pattern: Sanitization -> Filtration  
  
Fixing-commits Count: 1  
Total Change Size: +4 0  
## Sample logs: No  
## Logging statements:  
### Source labels:  
Type of Sensitive Information:authentication data -> sensitive information such as account passwords and authorization tokens  
### Sink labels:  
#### Sink 1:  
Logging call Function:  User-defined（wrap_exception）  
Sensitiveness-Identifiable Source:  Same Projects & Cross Modules（https://github.com/openstack/nova/blob/6dfcb16152a7d0b1f4ad53a0fc4186fb6472befe/nova/context.py#L62） -> Variable Names（auth_token）  
Programming Language:Python  
```Python  
  
# https://github.com/openstack/nova/blob/32b1aa24a6f45bd00165820f8b6e342ddc2867b6/nova/exception.py#L63-L93  
  
def wrap_exception(notifier=None, get_notifier=None):  
    """This decorator wraps a method to catch any exceptions that may  
    get thrown. It logs the exception as well as optionally sending  
    it to the notification system.  
    """  
    def inner(f):  
        def wrapped(self, context, *args, **kw):  
            # Don't store self or context in the payload, it now seems to  
            # contain confidential information.  
            try:  
                return f(self, context, *args, **kw)  
            except Exception as e:  
                with excutils.save_and_reraise_exception():  
                    if notifier or get_notifier:  
                        payload = dict(exception=e)  
                        call_dict = safe_utils.getcallargs(f, context,  
                                                           *args, **kw)  
                        cleansed = _cleanse_dict(call_dict)  
                        payload.update({'args': cleansed})  
  
                        # If f has multiple decorators, they must use  
                        # functools.wraps to ensure the name is  
                        # propagated.  
                        event_type = f.__name__  
  
                        (notifier or get_notifier()).error(context,  
                                                           event_type,  
                                                           payload) # HERE IS THE SINK 1  
  
        return functools.wraps(f)(wrapped)  
    return inner  
  
# https://github.com/openstack/nova/blob/6dfcb16152a7d0b1f4ad53a0fc4186fb6472befe/nova/compute/api.py#L6360-L6480  
  
    @wrap_exception() # HERE IS THE EXTERNAL SINK  
    @target_host_cell  
    def set_host_enabled(self, context, host_name, enabled):  
        """Sets the specified host's ability to accept new instances."""  
        host_name = self._assert_host_exists(context, host_name)  
        payload = {'host_name': host_name, 'enabled': enabled}  
        compute_utils.notify_about_host_update(context,  
                                               'set_enabled.start',  
                                               payload)  
        result = self.rpcapi.set_host_enabled(context, enabled=enabled,  
                host=host_name)  
        compute_utils.notify_about_host_update(context,  
                                               'set_enabled.end',  
                                               payload)  
        return result  
  
```  
