## Summary:  
Software: zuul  
## Fix:  
Commit: https://opendev.org/zuul/zuul/commit/ffe7278c08e6e36bf8b18f732c764e00ff51551e  
Change Size: +90 -1  
Author: Tobias Henkel  
Fix Time (of the Last Commit): 2018-06-08  
Fix Pattern: Sanitization -> Redaction -> Enhancement (Corrective Change) -> Tag/TypeBasedFiltration  
  
Fixing-commits Count: 1  
Total Change Size: +90 -1  
## Sample logs: Yes  
```  
2018-06-06 14:15:35.429104 | LOOP [ensure-netrc : Ensure netrc entries]  
2018-06-06 14:15:40.099687 | node | Output suppressed because no_log was given  
2018-06-06 14:15:40.105502 |   
2018-06-06 14:15:40.105761 | PLAY RECAP  
2018-06-06 14:15:40.105997 | node | ok: 1 changed: 0 unreachable: 1 failed: 0  
2018-06-06 14:15:40.106149 |   
2018-06-06 14:15:40.291161 | ANSIBLE PARSE ERROR  
2018-06-06 14:15:40.291219 | Using /tmp/4d422d7d99c64a79ad4159b0ba8c68c3/ansible/post_playbook_1/ansible.cfg as config file  
2018-06-06 14:15:40.291258 | fatal: [node]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"_ansible_ignore_errors": null, "_ansible_item_result": true, "item": {"login": “LEAKED_HERE”, "machine": “foo.example.com”, "password": “LEAKED_HERE”}, "msg": "SSH Error: data could not be sent to remote host \"10.136.0.74\". Make sure this host can be reached over ssh", "unreachable": true}]}  
```  
## Logging statements:  
### Source labels:  
Type of Sensitive Information:authentication data -> credentials or secrets, the contents of the loop items  
### Sink labels:  
#### Sink 1:  
Logging call Function:  Third-party Libaries（Display.display）  
Sensitiveness-Identifiable Source:  No  
#### Sink 2:  
Logging call Function:  Third-party Libaries（Display.display）  
Sensitiveness-Identifiable Source:  No  
#### Sink 3:  
Logging call Function:  Third-party Libaries（Display.display）  
Sensitiveness-Identifiable Source:  No  
Programming Language:Python  
```python  
# https://github.com/ansible/ansible/blob/4ca23cb147f1f72c2a2045d3a763e50fd6ab491b/lib/ansible/plugins/callback/default.py#L117-L127  
    def v2_runner_on_unreachable(self, result):  
        if self._play.strategy == 'free' and self._last_task_banner != result._task._uuid:  
            self._print_task_banner(result._task)  
  
        delegated_vars = result._result.get('_ansible_delegated_vars', None)  
        if delegated_vars:  
            self._display.display("fatal: [%s -> %s]: UNREACHABLE! => %s" % (result._host.get_name(), delegated_vars['ansible_host'],  
                                                                             self._dump_results(result._result)),  
                                  color=C.COLOR_UNREACHABLE) # HERE IS THE SINK 1  
        else:  
            self._display.display("fatal: [%s]: UNREACHABLE! => %s" % (result._host.get_name(), self._dump_results(result._result)), color=C.COLOR_UNREACHABLE) # HERE IS THE SINK 2  
  
# https://github.com/ansible/ansible/blob/4ca23cb147f1f72c2a2045d3a763e50fd6ab491b/lib/ansible/plugins/callback/default.py#L214-L227  
    def v2_runner_item_on_failed(self, result):  
  
        delegated_vars = result._result.get('_ansible_delegated_vars', None)  
        self._clean_results(result._result, result._task.action)  
        self._handle_exception(result._result)  
  
        msg = "failed: "  
        if delegated_vars:  
            msg += "[%s -> %s]" % (result._host.get_name(), delegated_vars['ansible_host'])  
        else:  
            msg += "[%s]" % (result._host.get_name())  
  
        self._handle_warnings(result._result)  
        self._display.display(msg + " (item=%s) => %s" % (self._get_item(result._result), self._dump_results(result._result)), color=C.COLOR_ERROR) # HERE IS THE SINK 3  
  
```  
