## Summary:  
Software: gitlab  
## Fix:  
Commit: https://gitlab.com/gitlab-org/gitaly/-/commit/c871668bacb677e3f8f4171bea357bfb09f76466  
Change Size: +21 -11  
Author: Oswaldo Ferreira  
Fix Time (of the Last Commit): 2019-04-17  
Fix Pattern: Sanitization -> Redaction -> Enhancement -> Keyword/RegexBasedFiltration -> RedactionFunctionDefined  
  
Fixing-commits Count: 1  
Total Change Size: +21 -11  
## Sample logs: Yes  
```  
2:Fetching remote remote_mirror_849955cdfae47542e830cb4d292d9bd4 failed: fatal: Unable to look up testuser1:passwordleak@192.168.0.16 (port 9418) (Name or service not known)  
```  
## Logging statements:  
### Source labels:  
Type of Sensitive Information:authentication data -> HTTP/GIT credentials  
### Sink labels:  
Sink Counts: 0  
Programming Language:Ruby  
```ruby  
# https://gitlab.com/gitlab-org/gitaly/-/blob/c871668bacb677e3f8f4171bea357bfb09f76466/ruby/lib/gitaly_server/repository_service.rb#L36  
  
    def fetch_remote(request, call)  
      gitlab_projects = Gitlab::Git::GitlabProjects.from_gitaly(request.repository, call)  
  
      success = Gitlab::Git::SshAuth.from_gitaly(request).setup do |env|  
        gitlab_projects.fetch_remote(  
          request.remote,  
          request.timeout,  
          force: request.force,  
          tags: !request.no_tags,  
          env: env  
        )  
      end  
  
      raise GRPC::Unknown.new("Fetching remote #{request.remote} failed: #{gitlab_projects.output}") unless success # HERE IS THE SINK 1  
  
      Gitaly::FetchRemoteResponse.new  
    end  
  
  
```  
